2025-03-09 11:45:35,680 [INFO] USER:priyanshukumar_jha handlers.py:106:syndicate LOG: Configuration used: C:\Users\priyanshukumar_jha\Desktop\demo\task04\.syndicate-config-dev
2025-03-09 11:45:35,693 [ERROR] USER:priyanshukumar_jha decorators.py:136:wrapper LOG: sdct.conf does not exist inside C:\Users\priyanshukumar_jha\Desktop\demo\task04\.syndicate-config-dev folder
2025-03-09 11:45:35,704 [ERROR] USER:priyanshukumar_jha decorators.py:137:wrapper LOG: Traceback (most recent call last):
  File "C:\Users\priyanshukumar_jha\AppData\Local\Programs\Python\Python313\Lib\site-packages\syndicate\core\decorators.py", line 134, in wrapper
    return_code = func(*args, **kwargs)
  File "C:\Users\priyanshukumar_jha\AppData\Local\Programs\Python\Python313\Lib\site-packages\syndicate\core\handlers.py", line 107, in syndicate
    initialize_connection()
    ~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\priyanshukumar_jha\AppData\Local\Programs\Python\Python313\Lib\site-packages\syndicate\core\__init__.py", line 106, in initialize_connection
    CONFIG = ConfigHolder(CONF_PATH)
  File "C:\Users\priyanshukumar_jha\AppData\Local\Programs\Python\Python313\Lib\site-packages\syndicate\core\conf\processor.py", line 63, in __init__
    self._init_conf_config(dir_path=dir_path)
    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "C:\Users\priyanshukumar_jha\AppData\Local\Programs\Python\Python313\Lib\site-packages\syndicate\core\conf\processor.py", line 92, in _init_conf_config
    raise AssertionError(
        'sdct.conf does not exist inside %s folder' % dir_path)
AssertionError: sdct.conf does not exist inside C:\Users\priyanshukumar_jha\Desktop\demo\task04\.syndicate-config-dev folder
Traceback (most recent call last):
  File "C:\Users\priyanshukumar_jha\AppData\Local\Programs\Python\Python313\Lib\site-packages\syndicate\core\decorators.py", line 134, in wrapper
    return_code = func(*args, **kwargs)
  File "C:\Users\priyanshukumar_jha\AppData\Local\Programs\Python\Python313\Lib\site-packages\syndicate\core\handlers.py", line 107, in syndicate
    initialize_connection()
    ~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\priyanshukumar_jha\AppData\Local\Programs\Python\Python313\Lib\site-packages\syndicate\core\__init__.py", line 106, in initialize_connection
    CONFIG = ConfigHolder(CONF_PATH)
  File "C:\Users\priyanshukumar_jha\AppData\Local\Programs\Python\Python313\Lib\site-packages\syndicate\core\conf\processor.py", line 63, in __init__
    self._init_conf_config(dir_path=dir_path)
    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "C:\Users\priyanshukumar_jha\AppData\Local\Programs\Python\Python313\Lib\site-packages\syndicate\core\conf\processor.py", line 92, in _init_conf_config
    raise AssertionError(
        'sdct.conf does not exist inside %s folder' % dir_path)
AssertionError: sdct.conf does not exist inside C:\Users\priyanshukumar_jha\Desktop\demo\task04\.syndicate-config-dev folder
